# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"\x90\x01\n\x0fmakePostRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bphoto_bytes\x18\x02 \x01(\x0c\x12\x12\n\npost_title\x18\x03 \x01(\t\x12\x18\n\x10post_description\x18\x04 \x01(\t\x12\x16\n\x0eseller_contact\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x03\"/\n\x10makePostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\"\xc2\x01\n\x0fGetPostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x13\n\x0bphoto_bytes\x18\x03 \x01(\x0c\x12\x12\n\npost_title\x18\x04 \x01(\t\x12\x18\n\x10post_description\x18\x05 \x01(\t\x12\x16\n\x0eseller_contact\x18\x06 \x01(\t\x12\x15\n\rcreation_time\x18\x07 \x01(\t\x12\x0f\n\x07post_id\x18\x08 \x01(\x05\x12\x0f\n\x07user_id\x18\t \x01(\x03\"A\n\x18GetPostPaginatedResponse\x12%\n\x05posts\x18\x01 \x03(\x0b\x32\x16.posts.GetPostResponse\"\x17\n\x15GetFirstPostIdRequest\"L\n\x16GetFirstPostIdResponse\x12\x15\n\rfirst_post_id\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"%\n\x12\x43heckPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"$\n\x13\x43heckPostIdResponse\x12\r\n\x05state\x18\x01 \x01(\x08\x32H\n\tpostMaker\x12;\n\x08makePost\x12\x16.posts.makePostRequest\x1a\x17.posts.makePostResponse2\xa7\x02\n\npostGetter\x12\x38\n\x07getPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponse\x12J\n\x10GetPostPaginated\x12\x15.posts.GetPostRequest\x1a\x1f.posts.GetPostPaginatedResponse\x12M\n\x0eGetFirstPostId\x12\x1c.posts.GetFirstPostIdRequest\x1a\x1d.posts.GetFirstPostIdResponse\x12\x44\n\x0b\x43heckPostId\x12\x19.posts.CheckPostIdRequest\x1a\x1a.posts.CheckPostIdResponseb\x06proto3')



_MAKEPOSTREQUEST = DESCRIPTOR.message_types_by_name['makePostRequest']
_MAKEPOSTRESPONSE = DESCRIPTOR.message_types_by_name['makePostResponse']
_GETPOSTREQUEST = DESCRIPTOR.message_types_by_name['GetPostRequest']
_GETPOSTRESPONSE = DESCRIPTOR.message_types_by_name['GetPostResponse']
_GETPOSTPAGINATEDRESPONSE = DESCRIPTOR.message_types_by_name['GetPostPaginatedResponse']
_GETFIRSTPOSTIDREQUEST = DESCRIPTOR.message_types_by_name['GetFirstPostIdRequest']
_GETFIRSTPOSTIDRESPONSE = DESCRIPTOR.message_types_by_name['GetFirstPostIdResponse']
_CHECKPOSTIDREQUEST = DESCRIPTOR.message_types_by_name['CheckPostIdRequest']
_CHECKPOSTIDRESPONSE = DESCRIPTOR.message_types_by_name['CheckPostIdResponse']
makePostRequest = _reflection.GeneratedProtocolMessageType('makePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAKEPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.makePostRequest)
  })
_sym_db.RegisterMessage(makePostRequest)

makePostResponse = _reflection.GeneratedProtocolMessageType('makePostResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAKEPOSTRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.makePostResponse)
  })
_sym_db.RegisterMessage(makePostResponse)

GetPostRequest = _reflection.GeneratedProtocolMessageType('GetPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostRequest)
  })
_sym_db.RegisterMessage(GetPostRequest)

GetPostResponse = _reflection.GeneratedProtocolMessageType('GetPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostResponse)
  })
_sym_db.RegisterMessage(GetPostResponse)

GetPostPaginatedResponse = _reflection.GeneratedProtocolMessageType('GetPostPaginatedResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTPAGINATEDRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostPaginatedResponse)
  })
_sym_db.RegisterMessage(GetPostPaginatedResponse)

GetFirstPostIdRequest = _reflection.GeneratedProtocolMessageType('GetFirstPostIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFIRSTPOSTIDREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetFirstPostIdRequest)
  })
_sym_db.RegisterMessage(GetFirstPostIdRequest)

GetFirstPostIdResponse = _reflection.GeneratedProtocolMessageType('GetFirstPostIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFIRSTPOSTIDRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetFirstPostIdResponse)
  })
_sym_db.RegisterMessage(GetFirstPostIdResponse)

CheckPostIdRequest = _reflection.GeneratedProtocolMessageType('CheckPostIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPOSTIDREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.CheckPostIdRequest)
  })
_sym_db.RegisterMessage(CheckPostIdRequest)

CheckPostIdResponse = _reflection.GeneratedProtocolMessageType('CheckPostIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPOSTIDRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.CheckPostIdResponse)
  })
_sym_db.RegisterMessage(CheckPostIdResponse)

_POSTMAKER = DESCRIPTOR.services_by_name['postMaker']
_POSTGETTER = DESCRIPTOR.services_by_name['postGetter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAKEPOSTREQUEST._serialized_start=23
  _MAKEPOSTREQUEST._serialized_end=167
  _MAKEPOSTRESPONSE._serialized_start=169
  _MAKEPOSTRESPONSE._serialized_end=216
  _GETPOSTREQUEST._serialized_start=218
  _GETPOSTREQUEST._serialized_end=251
  _GETPOSTRESPONSE._serialized_start=254
  _GETPOSTRESPONSE._serialized_end=448
  _GETPOSTPAGINATEDRESPONSE._serialized_start=450
  _GETPOSTPAGINATEDRESPONSE._serialized_end=515
  _GETFIRSTPOSTIDREQUEST._serialized_start=517
  _GETFIRSTPOSTIDREQUEST._serialized_end=540
  _GETFIRSTPOSTIDRESPONSE._serialized_start=542
  _GETFIRSTPOSTIDRESPONSE._serialized_end=618
  _CHECKPOSTIDREQUEST._serialized_start=620
  _CHECKPOSTIDREQUEST._serialized_end=657
  _CHECKPOSTIDRESPONSE._serialized_start=659
  _CHECKPOSTIDRESPONSE._serialized_end=695
  _POSTMAKER._serialized_start=697
  _POSTMAKER._serialized_end=769
  _POSTGETTER._serialized_start=772
  _POSTGETTER._serialized_end=1067
# @@protoc_insertion_point(module_scope)
