# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"\x90\x01\n\x0fmakePostRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bphoto_bytes\x18\x02 \x01(\x0c\x12\x12\n\npost_title\x18\x03 \x01(\t\x12\x18\n\x10post_description\x18\x04 \x01(\t\x12\x16\n\x0eseller_contact\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x03\"/\n\x10makePostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\"\x89\x01\n\x0fGetPostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x13\n\x0bphoto_bytes\x18\x03 \x01(\x0c\x12\x12\n\npost_title\x18\x04 \x01(\t\x12\x18\n\x10post_description\x18\x05 \x01(\t\x12\x16\n\x0eseller_contact\x18\x06 \x01(\t2H\n\tpostMaker\x12;\n\x08makePost\x12\x16.posts.makePostRequest\x1a\x17.posts.makePostResponse2F\n\npostGetter\x12\x38\n\x07getPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponseb\x06proto3')



_MAKEPOSTREQUEST = DESCRIPTOR.message_types_by_name['makePostRequest']
_MAKEPOSTRESPONSE = DESCRIPTOR.message_types_by_name['makePostResponse']
_GETPOSTREQUEST = DESCRIPTOR.message_types_by_name['GetPostRequest']
_GETPOSTRESPONSE = DESCRIPTOR.message_types_by_name['GetPostResponse']
makePostRequest = _reflection.GeneratedProtocolMessageType('makePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAKEPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.makePostRequest)
  })
_sym_db.RegisterMessage(makePostRequest)

makePostResponse = _reflection.GeneratedProtocolMessageType('makePostResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAKEPOSTRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.makePostResponse)
  })
_sym_db.RegisterMessage(makePostResponse)

GetPostRequest = _reflection.GeneratedProtocolMessageType('GetPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostRequest)
  })
_sym_db.RegisterMessage(GetPostRequest)

GetPostResponse = _reflection.GeneratedProtocolMessageType('GetPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostResponse)
  })
_sym_db.RegisterMessage(GetPostResponse)

_POSTMAKER = DESCRIPTOR.services_by_name['postMaker']
_POSTGETTER = DESCRIPTOR.services_by_name['postGetter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAKEPOSTREQUEST._serialized_start=23
  _MAKEPOSTREQUEST._serialized_end=167
  _MAKEPOSTRESPONSE._serialized_start=169
  _MAKEPOSTRESPONSE._serialized_end=216
  _GETPOSTREQUEST._serialized_start=218
  _GETPOSTREQUEST._serialized_end=251
  _GETPOSTRESPONSE._serialized_start=254
  _GETPOSTRESPONSE._serialized_end=391
  _POSTMAKER._serialized_start=393
  _POSTMAKER._serialized_end=465
  _POSTGETTER._serialized_start=467
  _POSTGETTER._serialized_end=537
# @@protoc_insertion_point(module_scope)
