# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services.profile.profile_pb2 as profile__pb2


class userGetterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser_ById = channel.unary_unary(
                '/profile.userGetter/GetUser_ById',
                request_serializer=profile__pb2.GetUserRequest.SerializeToString,
                response_deserializer=profile__pb2.GetUserResponse.FromString,
                )


class userGetterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser_ById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_userGetterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser_ById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser_ById,
                    request_deserializer=profile__pb2.GetUserRequest.FromString,
                    response_serializer=profile__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.userGetter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class userGetter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser_ById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.userGetter/GetUser_ById',
            profile__pb2.GetUserRequest.SerializeToString,
            profile__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
