# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\x9e\x01\n\x0fGetUserResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x03\x12\r\n\x05login\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x0f\n\x07surname\x18\x08 \x01(\t\x12\x0f\n\x07\x63ompany\x18\t \x01(\t2O\n\nuserGetter\x12\x41\n\x0cGetUser_ById\x12\x17.profile.GetUserRequest\x1a\x18.profile.GetUserResponseb\x06proto3')



_GETUSERREQUEST = DESCRIPTOR.message_types_by_name['GetUserRequest']
_GETUSERRESPONSE = DESCRIPTOR.message_types_by_name['GetUserResponse']
GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:profile.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

GetUserResponse = _reflection.GeneratedProtocolMessageType('GetUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERRESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:profile.GetUserResponse)
  })
_sym_db.RegisterMessage(GetUserResponse)

_USERGETTER = DESCRIPTOR.services_by_name['userGetter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSERREQUEST._serialized_start=26
  _GETUSERREQUEST._serialized_end=59
  _GETUSERRESPONSE._serialized_start=62
  _GETUSERRESPONSE._serialized_end=220
  _USERGETTER._serialized_start=222
  _USERGETTER._serialized_end=301
# @@protoc_insertion_point(module_scope)
