# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sessions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esessions.proto\x12\x08sessions\"+\n\x18\x43reatePostSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"N\n\x19\x43reatePostSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x14\n\x0csession_name\x18\x03 \x01(\t\"%\n\x12\x44ropSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"2\n\x13\x44ropSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t2\xc3\x01\n\x13postSessionsService\x12\\\n\x11\x43reatePostSession\x12\".sessions.CreatePostSessionRequest\x1a#.sessions.CreatePostSessionResponse\x12N\n\x0f\x44ropPostSession\x12\x1c.sessions.DropSessionRequest\x1a\x1d.sessions.DropSessionResponseb\x06proto3')



_CREATEPOSTSESSIONREQUEST = DESCRIPTOR.message_types_by_name['CreatePostSessionRequest']
_CREATEPOSTSESSIONRESPONSE = DESCRIPTOR.message_types_by_name['CreatePostSessionResponse']
_DROPSESSIONREQUEST = DESCRIPTOR.message_types_by_name['DropSessionRequest']
_DROPSESSIONRESPONSE = DESCRIPTOR.message_types_by_name['DropSessionResponse']
CreatePostSessionRequest = _reflection.GeneratedProtocolMessageType('CreatePostSessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOSTSESSIONREQUEST,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:sessions.CreatePostSessionRequest)
  })
_sym_db.RegisterMessage(CreatePostSessionRequest)

CreatePostSessionResponse = _reflection.GeneratedProtocolMessageType('CreatePostSessionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOSTSESSIONRESPONSE,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:sessions.CreatePostSessionResponse)
  })
_sym_db.RegisterMessage(CreatePostSessionResponse)

DropSessionRequest = _reflection.GeneratedProtocolMessageType('DropSessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DROPSESSIONREQUEST,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:sessions.DropSessionRequest)
  })
_sym_db.RegisterMessage(DropSessionRequest)

DropSessionResponse = _reflection.GeneratedProtocolMessageType('DropSessionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DROPSESSIONRESPONSE,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:sessions.DropSessionResponse)
  })
_sym_db.RegisterMessage(DropSessionResponse)

_POSTSESSIONSSERVICE = DESCRIPTOR.services_by_name['postSessionsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEPOSTSESSIONREQUEST._serialized_start=28
  _CREATEPOSTSESSIONREQUEST._serialized_end=71
  _CREATEPOSTSESSIONRESPONSE._serialized_start=73
  _CREATEPOSTSESSIONRESPONSE._serialized_end=151
  _DROPSESSIONREQUEST._serialized_start=153
  _DROPSESSIONREQUEST._serialized_end=190
  _DROPSESSIONRESPONSE._serialized_start=192
  _DROPSESSIONRESPONSE._serialized_end=242
  _POSTSESSIONSSERVICE._serialized_start=245
  _POSTSESSIONSSERVICE._serialized_end=440
# @@protoc_insertion_point(module_scope)
