# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthorization.proto\x12\rauthorization\"0\n\rSingUpRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x14SingUpByTokenRequest\x12\r\n\x05token\x18\x01 \x01(\x0c\"\x9d\x01\n\x0eSingUpResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x03\x12\r\n\x05login\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x0f\n\x07surname\x18\x08 \x01(\t\x12\x0f\n\x07\x63ompany\x18\t \x01(\t2\xa8\x01\n\nauthorizer\x12\x45\n\x06SingUp\x12\x1c.authorization.SingUpRequest\x1a\x1d.authorization.SingUpResponse\x12S\n\rSingUpByToken\x12#.authorization.SingUpByTokenRequest\x1a\x1d.authorization.SingUpResponseb\x06proto3')



_SINGUPREQUEST = DESCRIPTOR.message_types_by_name['SingUpRequest']
_SINGUPBYTOKENREQUEST = DESCRIPTOR.message_types_by_name['SingUpByTokenRequest']
_SINGUPRESPONSE = DESCRIPTOR.message_types_by_name['SingUpResponse']
SingUpRequest = _reflection.GeneratedProtocolMessageType('SingUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGUPREQUEST,
  '__module__' : 'authorization_pb2'
  # @@protoc_insertion_point(class_scope:authorization.SingUpRequest)
  })
_sym_db.RegisterMessage(SingUpRequest)

SingUpByTokenRequest = _reflection.GeneratedProtocolMessageType('SingUpByTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGUPBYTOKENREQUEST,
  '__module__' : 'authorization_pb2'
  # @@protoc_insertion_point(class_scope:authorization.SingUpByTokenRequest)
  })
_sym_db.RegisterMessage(SingUpByTokenRequest)

SingUpResponse = _reflection.GeneratedProtocolMessageType('SingUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SINGUPRESPONSE,
  '__module__' : 'authorization_pb2'
  # @@protoc_insertion_point(class_scope:authorization.SingUpResponse)
  })
_sym_db.RegisterMessage(SingUpResponse)

_AUTHORIZER = DESCRIPTOR.services_by_name['authorizer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SINGUPREQUEST._serialized_start=38
  _SINGUPREQUEST._serialized_end=86
  _SINGUPBYTOKENREQUEST._serialized_start=88
  _SINGUPBYTOKENREQUEST._serialized_end=125
  _SINGUPRESPONSE._serialized_start=128
  _SINGUPRESPONSE._serialized_end=285
  _AUTHORIZER._serialized_start=288
  _AUTHORIZER._serialized_end=456
# @@protoc_insertion_point(module_scope)
