# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12registration.proto\x12\x0cregistration\"\x83\x01\n\rSingInRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x05 \x01(\t\x12\x12\n\nbirth_date\x18\x06 \x01(\t\x12\r\n\x05token\x18\x07 \x01(\x0c\"-\n\x0eSingInResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t2P\n\tregistrar\x12\x43\n\x06SingIn\x12\x1b.registration.SingInRequest\x1a\x1c.registration.SingInResponseb\x06proto3')



_SINGINREQUEST = DESCRIPTOR.message_types_by_name['SingInRequest']
_SINGINRESPONSE = DESCRIPTOR.message_types_by_name['SingInResponse']
SingInRequest = _reflection.GeneratedProtocolMessageType('SingInRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGINREQUEST,
  '__module__' : 'registration_pb2'
  # @@protoc_insertion_point(class_scope:registration.SingInRequest)
  })
_sym_db.RegisterMessage(SingInRequest)

SingInResponse = _reflection.GeneratedProtocolMessageType('SingInResponse', (_message.Message,), {
  'DESCRIPTOR' : _SINGINRESPONSE,
  '__module__' : 'registration_pb2'
  # @@protoc_insertion_point(class_scope:registration.SingInResponse)
  })
_sym_db.RegisterMessage(SingInResponse)

_REGISTRAR = DESCRIPTOR.services_by_name['registrar']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SINGINREQUEST._serialized_start=37
  _SINGINREQUEST._serialized_end=168
  _SINGINRESPONSE._serialized_start=170
  _SINGINRESPONSE._serialized_end=215
  _REGISTRAR._serialized_start=217
  _REGISTRAR._serialized_end=297
# @@protoc_insertion_point(module_scope)
