# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services.registrar.registration_pb2 as registration__pb2


class registrarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SingIn = channel.unary_unary(
                '/registration.registrar/SingIn',
                request_serializer=registration__pb2.SingInRequest.SerializeToString,
                response_deserializer=registration__pb2.SingInResponse.FromString,
                )


class registrarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SingIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_registrarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SingIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SingIn,
                    request_deserializer=registration__pb2.SingInRequest.FromString,
                    response_serializer=registration__pb2.SingInResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'registration.registrar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class registrar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SingIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/registration.registrar/SingIn',
            registration__pb2.SingInRequest.SerializeToString,
            registration__pb2.SingInResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
