# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tyml.proto\x12\x03yml\"2\n\rUploadRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\x03\x12\x0e\n\x06ymlUrl\x18\x02 \x01(\t\"-\n\x0eUploadResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t2F\n\x0cYmlPostMaker\x12\x36\n\x0bUploadPosts\x12\x12.yml.UploadRequest\x1a\x13.yml.UploadResponseb\x06proto3')



_UPLOADREQUEST = DESCRIPTOR.message_types_by_name['UploadRequest']
_UPLOADRESPONSE = DESCRIPTOR.message_types_by_name['UploadResponse']
UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQUEST,
  '__module__' : 'yml_pb2'
  # @@protoc_insertion_point(class_scope:yml.UploadRequest)
  })
_sym_db.RegisterMessage(UploadRequest)

UploadResponse = _reflection.GeneratedProtocolMessageType('UploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADRESPONSE,
  '__module__' : 'yml_pb2'
  # @@protoc_insertion_point(class_scope:yml.UploadResponse)
  })
_sym_db.RegisterMessage(UploadResponse)

_YMLPOSTMAKER = DESCRIPTOR.services_by_name['YmlPostMaker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPLOADREQUEST._serialized_start=18
  _UPLOADREQUEST._serialized_end=68
  _UPLOADRESPONSE._serialized_start=70
  _UPLOADRESPONSE._serialized_end=115
  _YMLPOSTMAKER._serialized_start=117
  _YMLPOSTMAKER._serialized_end=187
# @@protoc_insertion_point(module_scope)
